# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '(?x)(\.idea |junit |lightgbm/common\.pyi$)'
      - id: check-docstring-first
      - id: debug-statements
      - id: check-yaml
      - id: check-ast
      - id: check-toml
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--line-length=110]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        args: [ --python-version=3.9,
                --config-file=mypy.ini,
                --disallow-untyped-calls,
                --disallow-untyped-defs,
                --disallow-incomplete-defs,
                --check-untyped-defs,
                --no-implicit-optional,
                --warn-redundant-casts,
                --ignore-missing-imports,
                --install-types,
                --non-interactive
        ]
        exclude: '(?x)(tests |\.idea |junit |examplerepo/common\.pyi$)'
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear==20.1.4"]
        args: [--max-line-length=110]
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args: [ "--in-place", "--remove-all-unused-imports" ]
