name: Test Azure Authentication
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
  PYTHON_VERSION: 3.8
  DATABRICKS_RESOURCE_ID: 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d

jobs:
  login-and-test:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install databricks CLI
      uses: microsoft/install-databricks-cli@v1.0.0

    - name: Configure DBR CLI & test
      run: |
        export DATABRICKS_AAD_TOKEN=$(az account get-access-token --resource ${{ env.DATABRICKS_RESOURCE_ID }} | jq -r .accessToken)
        databricks configure --aad-token --host ${{ secrets.DATABRICKS_HOST }}
        databricks clusters list
